In [1]:
import xarray as xr

In [2]:
PREDICTAND = "tasmean"

In [3]:
y_pred = xr.open_dataset("/mnt/CEPH_PROJECTS/InterTwin/Climate_Downscaling/larger_alps/ml_Predictions/tasmean/LGBMRegressor_tasmean_ztuvq_500_850_mslpt2_0mm_dem_sa_doy.nc")
y_pred = y_pred - 273.15
tasmean = y_pred[PREDICTAND].mean(dim='number')
y_pred = tasmean.to_dataset(name=PREDICTAND)
TIME = y_pred.time
y_pred = y_pred.to_array(dim='tasmean')
#y_pred = y_pred.to_numpy()
#y_pred = y_pred.squeeze()
y_pred

<xarray.DataArray (tasmean: 1, time: 212, y: 103, x: 125)>
array([[[[ 7.72992181,  7.76137797,  7.90259751, ..., -3.58784406,
          -3.58025228, -4.23525384],
         [ 8.07092527,  8.08309698,  8.22543106, ..., -3.64586629,
          -3.17780297, -3.24331951],
         [ 8.07818235,  7.88423565,  7.89225107, ..., -4.10674774,
          -3.65041684, -3.06805921],
         ...,
         [11.14489214, 11.0243541 , 11.43454073, ...,  7.91762593,
           8.20217928,  7.47580986],
         [11.12653261, 11.4400968 , 11.8138119 , ...,  5.83254425,
           5.76033374,  6.21622311],
         [11.18507828, 11.7112482 , 11.93552473, ...,  7.72432012,
           7.81314895,  6.5505505 ]],

        [[ 5.84796876,  5.85247759,  6.02486776, ..., -6.70054147,
          -6.73794431, -6.92108824],
         [ 6.08741825,  6.17571107,  6.29867026, ..., -6.50894526,
          -6.05119382, -5.90679189],
         [ 6.08791306,  5.8779673 ,  5.84092175, ..., -5.76236133,
          -5.95540245, -5.75894995],
...
         [22.48861889, 22.59219998, 22.87656403, ..., 24.88472119,
          24.95241546, 24.10317463],
         [22.40868605, 22.63648202, 22.63881812, ..., 23.82105352,
          24.25164633, 24.28681674],
         [22.40178618, 22.71367064, 22.69397136, ..., 24.44466574,
          24.49470866, 24.25333528]],

        [[17.74565509, 17.82685087, 18.11353062, ..., 16.95643113,
          17.26620732, 17.25782942],
         [18.15302547, 18.65594113, 18.70842046, ..., 16.16260353,
          17.18432555, 18.16795226],
         [18.3235837 , 18.04424278, 18.070275  , ..., 14.92212413,
          15.43194196, 17.30763855],
         ...,
         [22.44261294, 22.54059105, 22.77970888, ..., 24.76418299,
          24.86065122, 24.02183998],
         [22.32952133, 22.59606884, 22.58435754, ..., 23.68534892,
          24.12278984, 24.16515142],
         [22.35235701, 22.62326711, 22.59611489, ..., 24.3617294 ,
          24.395845  , 24.13870856]]]])
Coordinates:
  * time     (time) datetime64[ns] 2016-01-02 2016-01-03 ... 2016-07-31
  * y        (y) float64 50.52 50.45 50.37 50.3 50.23 ... 43.27 43.2 43.13 43.05
  * x        (x) float64 3.715 3.822 3.93 4.038 ... 16.75 16.85 16.96 17.07
  * tasmean  (tasmean) object 'tasmean'

In [4]:
y_pred.shape

(1, 212, 103, 125)

In [5]:
y_true = xr.open_dataset("/mnt/CEPH_PROJECTS/InterTwin/Climate_Downscaling/larger_alps/CERRA/tasmean/CERRA_2m_temperature_1985_2020.nc")    
y_true = y_true.rename({'longitude': "x"})
y_true = y_true.rename({'latitude': "y"})
y_true = y_true.sel(time=TIME)
y_true = y_true.rename({'t2m': PREDICTAND})
y_true = y_true - 273.15
y_true = y_true.drop_vars("heightAboveGround")
y_true = y_true.transpose('time', 'y', 'x')
y_true = y_true.to_array(dim='tasmean')
#y_true = y_true.to_numpy()
#y_true = y_true.squeeze()
y_true

<xarray.DataArray (tasmean: 1, time: 212, y: 103, x: 125)>
array([[[[  8.403107 ,   8.346222 ,   8.308624 , ...,  -7.0691223,
           -7.2671204,  -7.5451355],
         [  8.6692505,   8.613159 ,   8.562378 , ...,  -7.35318  ,
           -7.1090393,  -6.832947 ],
         [  8.386017 ,   8.023041 ,   8.061005 , ...,  -7.0759583,
           -7.492523 ,  -6.8048706],
         ...,
         [ 13.420258 ,  13.546875 ,  13.651337 , ...,  10.586761 ,
           10.632629 ,   9.359131 ],
         [ 13.460358 ,  13.566895 ,  13.681824 , ...,   8.985657 ,
            8.953613 ,   8.641937 ],
         [ 13.478363 ,  13.575775 ,  13.668579 , ...,  11.328552 ,
           10.776642 ,   9.357758 ]],

        [[  6.50412  ,   6.4684753,   6.4767456, ..., -11.638458 ,
          -11.618317 , -11.654724 ],
         [  6.704651 ,   6.676483 ,   6.696594 , ..., -11.883148 ,
          -11.638763 , -11.307587 ],
         [  6.4444885,   6.1457825,   6.2534485, ..., -11.593201 ,
          -11.912079 , -11.471893 ],
...
         [ 22.085785 ,  22.181244 ,  22.233002 , ...,  27.409332 ,
           27.288544 ,  27.110962 ],
         [ 22.14914  ,  22.217438 ,  22.262756 , ...,  27.823914 ,
           27.806    ,  27.89096  ],
         [ 22.237762 ,  22.277618 ,  22.290955 , ...,  25.957397 ,
           26.008087 ,  26.46698  ]],

        [[ 17.314636 ,  17.216858 ,  17.456696 , ...,  21.080322 ,
           21.06314  ,  21.085663 ],
         [ 17.554138 ,  17.911224 ,  18.093811 , ...,  20.422455 ,
           20.97815  ,  21.421173 ],
         [ 17.56012  ,  17.520782 ,  17.650665 , ...,  19.939575 ,
           19.552277 ,  20.77478  ],
         ...,
         [ 23.566742 ,  23.52835  ,  23.496857 , ...,  27.947388 ,
           27.895477 ,  28.06543  ],
         [ 23.402557 ,  23.466187 ,  23.451447 , ...,  28.208954 ,
           28.371796 ,  28.406006 ],
         [ 23.279755 ,  23.3078   ,  23.332367 , ...,  26.370941 ,
           26.518402 ,  26.972382 ]]]], dtype=float32)
Coordinates:
  * x        (x) float64 3.715 3.822 3.93 4.038 ... 16.75 16.85 16.96 17.07
  * y        (y) float64 50.52 50.45 50.37 50.3 50.23 ... 43.27 43.2 43.13 43.05
  * time     (time) datetime64[ns] 2016-01-02 2016-01-03 ... 2016-07-31
  * tasmean  (tasmean) object 'tasmean'
Attributes:
    CDI:                     Climate Data Interface version 2.0.4 (https://mp...
    Conventions:             CF-1.7
    institution:             Norrkoping
    GRIB_centre:             eswi
    GRIB_centreDescription:  Norrkoping
    history:                 Sun Jul 09 20:20:26 2023: cdo remapbil,/mnt/CEPH...
    CDO:                     Climate Data Operators version 2.0.4 (https://mp...

In [6]:
y_pred = y_pred.squeeze()

In [7]:
y_true = y_true.squeeze()

In [8]:
y_true

<xarray.DataArray (time: 212, y: 103, x: 125)>
array([[[  8.403107 ,   8.346222 ,   8.308624 , ...,  -7.0691223,
          -7.2671204,  -7.5451355],
        [  8.6692505,   8.613159 ,   8.562378 , ...,  -7.35318  ,
          -7.1090393,  -6.832947 ],
        [  8.386017 ,   8.023041 ,   8.061005 , ...,  -7.0759583,
          -7.492523 ,  -6.8048706],
        ...,
        [ 13.420258 ,  13.546875 ,  13.651337 , ...,  10.586761 ,
          10.632629 ,   9.359131 ],
        [ 13.460358 ,  13.566895 ,  13.681824 , ...,   8.985657 ,
           8.953613 ,   8.641937 ],
        [ 13.478363 ,  13.575775 ,  13.668579 , ...,  11.328552 ,
          10.776642 ,   9.357758 ]],

       [[  6.50412  ,   6.4684753,   6.4767456, ..., -11.638458 ,
         -11.618317 , -11.654724 ],
        [  6.704651 ,   6.676483 ,   6.696594 , ..., -11.883148 ,
         -11.638763 , -11.307587 ],
        [  6.4444885,   6.1457825,   6.2534485, ..., -11.593201 ,
         -11.912079 , -11.471893 ],
...
        [ 22.085785 ,  22.181244 ,  22.233002 , ...,  27.409332 ,
          27.288544 ,  27.110962 ],
        [ 22.14914  ,  22.217438 ,  22.262756 , ...,  27.823914 ,
          27.806    ,  27.89096  ],
        [ 22.237762 ,  22.277618 ,  22.290955 , ...,  25.957397 ,
          26.008087 ,  26.46698  ]],

       [[ 17.314636 ,  17.216858 ,  17.456696 , ...,  21.080322 ,
          21.06314  ,  21.085663 ],
        [ 17.554138 ,  17.911224 ,  18.093811 , ...,  20.422455 ,
          20.97815  ,  21.421173 ],
        [ 17.56012  ,  17.520782 ,  17.650665 , ...,  19.939575 ,
          19.552277 ,  20.77478  ],
        ...,
        [ 23.566742 ,  23.52835  ,  23.496857 , ...,  27.947388 ,
          27.895477 ,  28.06543  ],
        [ 23.402557 ,  23.466187 ,  23.451447 , ...,  28.208954 ,
          28.371796 ,  28.406006 ],
        [ 23.279755 ,  23.3078   ,  23.332367 , ...,  26.370941 ,
          26.518402 ,  26.972382 ]]], dtype=float32)
Coordinates:
  * x        (x) float64 3.715 3.822 3.93 4.038 ... 16.75 16.85 16.96 17.07
  * y        (y) float64 50.52 50.45 50.37 50.3 50.23 ... 43.27 43.2 43.13 43.05
  * time     (time) datetime64[ns] 2016-01-02 2016-01-03 ... 2016-07-31
    tasmean  <U7 'tasmean'
Attributes:
    CDI:                     Climate Data Interface version 2.0.4 (https://mp...
    Conventions:             CF-1.7
    institution:             Norrkoping
    GRIB_centre:             eswi
    GRIB_centreDescription:  Norrkoping
    history:                 Sun Jul 09 20:20:26 2023: cdo remapbil,/mnt/CEPH...
    CDO:                     Climate Data Operators version 2.0.4 (https://mp...

In [9]:
y_pred

<xarray.DataArray (time: 212, y: 103, x: 125)>
array([[[ 7.72992181,  7.76137797,  7.90259751, ..., -3.58784406,
         -3.58025228, -4.23525384],
        [ 8.07092527,  8.08309698,  8.22543106, ..., -3.64586629,
         -3.17780297, -3.24331951],
        [ 8.07818235,  7.88423565,  7.89225107, ..., -4.10674774,
         -3.65041684, -3.06805921],
        ...,
        [11.14489214, 11.0243541 , 11.43454073, ...,  7.91762593,
          8.20217928,  7.47580986],
        [11.12653261, 11.4400968 , 11.8138119 , ...,  5.83254425,
          5.76033374,  6.21622311],
        [11.18507828, 11.7112482 , 11.93552473, ...,  7.72432012,
          7.81314895,  6.5505505 ]],

       [[ 5.84796876,  5.85247759,  6.02486776, ..., -6.70054147,
         -6.73794431, -6.92108824],
        [ 6.08741825,  6.17571107,  6.29867026, ..., -6.50894526,
         -6.05119382, -5.90679189],
        [ 6.08791306,  5.8779673 ,  5.84092175, ..., -5.76236133,
         -5.95540245, -5.75894995],
...
        [22.48861889, 22.59219998, 22.87656403, ..., 24.88472119,
         24.95241546, 24.10317463],
        [22.40868605, 22.63648202, 22.63881812, ..., 23.82105352,
         24.25164633, 24.28681674],
        [22.40178618, 22.71367064, 22.69397136, ..., 24.44466574,
         24.49470866, 24.25333528]],

       [[17.74565509, 17.82685087, 18.11353062, ..., 16.95643113,
         17.26620732, 17.25782942],
        [18.15302547, 18.65594113, 18.70842046, ..., 16.16260353,
         17.18432555, 18.16795226],
        [18.3235837 , 18.04424278, 18.070275  , ..., 14.92212413,
         15.43194196, 17.30763855],
        ...,
        [22.44261294, 22.54059105, 22.77970888, ..., 24.76418299,
         24.86065122, 24.02183998],
        [22.32952133, 22.59606884, 22.58435754, ..., 23.68534892,
         24.12278984, 24.16515142],
        [22.35235701, 22.62326711, 22.59611489, ..., 24.3617294 ,
         24.395845  , 24.13870856]]])
Coordinates:
  * time     (time) datetime64[ns] 2016-01-02 2016-01-03 ... 2016-07-31
  * y        (y) float64 50.52 50.45 50.37 50.3 50.23 ... 43.27 43.2 43.13 43.05
  * x        (x) float64 3.715 3.822 3.93 4.038 ... 16.75 16.85 16.96 17.07
    tasmean  <U7 'tasmean'

In [10]:
-

SyntaxError: invalid syntax (476313318.py, line 1)

In [14]:
from bias_correction import BiasCorrection, XBiasCorrection
import pandas as pd

In [15]:
xbc = XBiasCorrection(y_true, y_pred, y_pred)
corrected = xbc.correct(method='basic_quantile')
corrected

<xarray.DataArray (y: 103, x: 125, time: 212)>
array([[[  8.57450959,   7.26660404,   6.7706127 , ...,  17.73600307,
          17.36001491,  18.95744987],
        [  8.5233242 ,   7.22628824,   6.73580233, ...,  17.91256645,
          17.33362408,  19.00897942],
        [  8.50411657,   7.25888787,   6.81512888, ...,  18.10977718,
          17.49352401,  19.1681466 ],
        ...,
        [ -7.15860398,  -9.40539734, -10.87417944, ...,  21.08114519,
          19.02433378,  18.57842544],
        [ -6.51076836, -10.76692511,  -9.10231184, ...,  21.32355187,
          19.3939245 ,  18.7251515 ],
        [ -7.917705  ,  -8.75369214, -10.33601452, ...,  21.08344957,
          19.59461363,  18.81979106]],

       [[  8.78280165,   7.56623904,   6.95837364, ...,  18.23464853,
          17.77958974,  19.2264237 ],
        [  8.76536693,   7.39951602,   6.72057995, ...,  18.52392888,
          18.06959778,  19.60242859],
        [  8.78530283,   7.47712182,   6.72945198, ...,  18.74729452,
          18.12842573,  19.83194533],
...
        [ 10.39825371,  10.14100525,   5.84916875, ...,  28.62305675,
          28.91854229,  28.50439023],
        [  9.82259773,  10.16194078,   6.27744368, ...,  28.55155193,
          28.97037042,  28.80884484],
        [ 10.2695357 ,  10.27357988,   5.56810687, ...,  27.85785298,
          28.05292946,  28.0390904 ]],

       [[ 13.59605686,   8.50895985,  12.98014802, ...,  24.14685059,
          23.71534709,  23.2811838 ],
        [ 13.73950236,   8.99024002,  13.21140578, ...,  24.084198  ,
          23.66274549,  23.35012923],
        [ 13.7125966 ,   9.55395521,  13.36543346, ...,  24.10214233,
          23.83959944,  23.48989106],
        ...,
        [ 12.49559247,  12.45651297,   5.39803065, ...,  26.86988254,
          27.20157409,  27.09384992],
        [ 13.28201497,  11.88711907,   5.21190574, ...,  26.95033629,
          27.45550243,  27.3165935 ],
        [ 10.77801476,  11.66943695,   6.61189957, ...,  26.93875825,
          27.26420611,  26.98361029]]])
Coordinates:
  * x        (x) float64 3.715 3.822 3.93 4.038 ... 16.75 16.85 16.96 17.07
  * y        (y) float64 50.52 50.45 50.37 50.3 50.23 ... 43.27 43.2 43.13 43.05
  * time     (time) datetime64[ns] 2016-01-02 2016-01-03 ... 2016-07-31
    tasmean  <U7 'tasmean'

In [16]:
prediction = corrected.to_numpy()
prediction = prediction.transpose(2, 0, 1)
prediction.shape
# store predictions in xarray.Dataset
predictions = xr.DataArray(data=prediction, dims=['time', 'y', 'x'],
                        coords=dict(time=pd.date_range(corrected.time.values[0],corrected.time.values[-1], freq='D'),
                                    lat=corrected.y, lon=corrected.x))
predictions = predictions.to_dataset(name=PREDICTAND)

predictions = predictions.set_index(
    time='time',
    y='lat',
    x='lon'
)

predictions.to_netcdf("basic_bias_corrected_sm.nc")
